services:
  mongo:
    image: mongo:latest
    container_name: mongo_dev_questionnaires
    ports:
      - '27017:27017'
    volumes:
      - ./mongo_questionnaires:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
