export enum RabbitMQ {
  QuestionnairesQueue = 'questionnaires',
}

export enum QuestionnaireMsg {
  CREATE = 'CREATE_QUESTIONNAIRE',
  FIND_ALL = 'FIND_QUESTIONNAIRES',
  FIND_ONE = 'FIND_QUESTIONNAIRE',
  UPDATE = 'UPDATE_QUESTIONNAIRE',
  DELETE = 'DELETE_QUESTIONNAIRE',
}

export enum QuestionMsg {
  CREATE = 'CREATE_QUESTION',
  FIND_ALL = 'FIND_QUESTIONS',
  FIND_ONE = 'FIND_QUESTION',
  UPDATE = 'UPDATE_QUESTION',
  DELETE = 'DELETE_QUESTION',
}
